DatVeXemPhim/Models/Phim.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DatVeXemPhim.Models
{
    public class Phim
    {
        public int id { get; set; }
        [DisplayName("Ảnh phim")]
        public string? posterPhim { get; set; }
            
        [Required]
        [DisplayName("Tên phim")]
        public string? tenPhim { get; set; }

        [DisplayName("Đạo diễn")]
        public string? daoDien { get; set; }

        [DisplayName("Diễn viên")]
        public string? dienVien { get; set; }

        [Required]
        [DisplayName("Mã loại phim")]
        public int maLoaiPhim { get; set; }
        [ForeignKey("maLoaiPhim")]
        public virtual TheLoaiPhim? fk_TheLoaiPhim { get; set; }

        [DisplayName("Thời gian khởi chiếu")]
        public DateTime thoiGianKhoiChieu { get; set; }

        [DisplayName("Thời lượng")]

        public string? thoiLuong { get; set; }

        [DisplayName("Ngôn ngữ")]
        public string? ngonNgu { get; set; }
        public ICollection<XuatChieu>? XuatChieus { get; set; }
    }
}

DatVeXemPhim/Controllers/HomeController.cs
using DatVeXemPhim.App_Start;
using DatVeXemPhim.Data;
using DatVeXemPhim.Models;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace DatVeXemPhim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DatVeXemPhimContext _context;

        public HomeController(ILogger<HomeController> logger, DatVeXemPhimContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()    
        {
            return View(await _context.Phim.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Dangnhap()
        {
            return View();
        }

        public IActionResult Phim()
        {
            return View();
        }

        public async Task<IActionResult> Search(string searchString)
        {

            ViewBag.SearchString = searchString;

            if (_context.Phim == null)
            {
                return Problem("Danh sách trống");
            }

            var movies = from m in _context.Phim
                         select m;
            var k = movies.Count();
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.tenPhim!.Contains(searchString));  
            }
            var a = 5;
            return View(await movies.ToListAsync());
        }
        public IActionResult Ve()
        {
            return View();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phim = await _context.Phim
                .Include(p => p.fk_TheLoaiPhim)
                .FirstOrDefaultAsync(m => m.id == id);
            if (phim == null)
            {
                return NotFound();
            }
            await _context.SaveChangesAsync();
            return View(phim);
        }

        public async Task<IActionResult> VeDaDat()
        {
            var user = SessionConfig.GetKhachHang();
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }


            int userId = user.id;
            var dsve = await _context.Ve
                .Where(v => v.maKhachHang == userId)
                .Include(p => p.fk_MaGhe)
                .Include(p => p.fk_XuatChieu)
                .ThenInclude(x => x.fk_Phim)
                .Include(p => p.fk_MaGhe)
                .ThenInclude(g => g.fk_PhongChieu)
                .ToListAsync();
            
            if (dsve == null || dsve.Count == 0)
            {
                return View();
            }
            return View(dsve);
        }
    }
}

DatVeXemPhim/Controllers/KhachDatVeController.cs
using DatVeXemPhim.App_Start;
using DatVeXemPhim.Data;
using DatVeXemPhim.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DatVeXemPhim.Controllers
{
    public class KhachDatVeController : Controller
    {
        private readonly DatVeXemPhimContext _context;

        public KhachDatVeController(DatVeXemPhimContext context)
        {
            _context = context;
        }

        // GET: Step2
        public async Task<IActionResult> Step2(int? id)
        {
            // Kiểm tra xem có người dùng nào đã đăng nhập hay không
            var khachHang = SessionConfig.GetKhachHang();

            if (khachHang == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var currentDateTime = DateTime.Now;

            var hasUpcomingShowtime = _context.XuatChieu
                .Where(x => x.maPhim == id && x.ngayChieu >= currentDateTime)
                .ToList();

            if (!hasUpcomingShowtime.Any())
            {
                return RedirectToAction("Index", "Home");
            }


            var xuatChieus = _context.XuatChieu.ToList();

            // Lấy danh sách các ghế đã được chọn


            ViewBag.UpcomingShowtimes = new SelectList(hasUpcomingShowtime,"id", "ngayChieu");

            var selectedSeats = _context.Ve.Select(v => v.maGhe).ToList();

            var availableSeats = _context.Ghe.Where(g => !selectedSeats.Contains(g.id)).ToList();

            ViewBag.Ghes = new SelectList(availableSeats, "id", "tenGhe");

            return View();
        }

        // POST: Step2
        [HttpPost]
        public IActionResult Step2(Ve ve)
        {
            if (ModelState.IsValid)
            {
                // Lấy thông tin khách hàng từ database
                var khachHang = SessionConfig.GetKhachHang().id;
                var xuatChieu = _context.XuatChieu.FirstOrDefault(x => x.id == ve.maXuatChieu);
                var ghe = _context.Ghe.FirstOrDefault(g => g.id == ve.maGhe);
                // Lấy thông tin nhân viên có id = 1 từ database
                var nhanVien = 1;

                Ve ves = new Ve
                {
                    maXuatChieu = xuatChieu.id,
                    maKhachHang = khachHang,
                    maGhe = ghe.id,
                    maNhanVien = nhanVien,
                    ngayBanVe = DateTime.Now, // Cập nhật ngày bán vé
                    tongTien = 45000 // Giá vé mặc định
                };

                _context.Ve.Add(ves);

                _context.SaveChanges();

                return RedirectToAction("VeDaDat", "Home");
            }
                
        // Nếu ModelState không hợp lệ, lấy lại danh sách để hiển th

            return View(ve);
        }

        // GET: Confirmation
        public IActionResult Confirmation(int id)
        {
            // Lấy thông tin của vé từ database dựa trên id đã được truyền từ action Step2
            var ve = _context.Ve
                .Include(v => v.fk_XuatChieu)
                .ThenInclude(x => x.fk_Phim)
                .Include(v => v.fk_MaGhe)
                .FirstOrDefault(v => v.id == id);

            if (ve == null)
            {
                return NotFound(); // Trường hợp không tìm thấy vé
            }

            return View(ve); // Trả về view Confirmation với dữ liệu của vé
        }
    }
}

DatVeXemPhim/Controllers/PhimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DatVeXemPhim.Data;
using DatVeXemPhim.Models;
using Microsoft.AspNetCore.Razor.Runtime.TagHelpers;

namespace DatVeXemPhim.Controllers
{
    public class PhimsController : Controller
    {
        private readonly DatVeXemPhimContext _context; //Khai báo một đối tượng context của Entity Framework để truy cập cơ sở dữ liệu.

        public PhimsController(DatVeXemPhimContext context) //Constructor nhận một đối tượng context và gán nó cho biến _context.
        {
            _context = context;
        }

        // GET: Phims
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? pageNumber)//Phương thức này xử lý yêu cầu GET để hiển thị danh sách các phim với khả năng tìm kiếm và phân trang.
        {
            ViewData["CurrentFilter"] = searchString; // Lưu trữ giá trị của searchString để sử dụng trong view.

            if (searchString != null)//Nếu có giá trị tìm kiếm mới, đặt pageNumber về 1
            {
                pageNumber = 1;
            }
            else //ngược lại sử dụng giá trị hiện tại.
            {
                searchString = currentFilter;
            }


            var phim = from s in _context.Phim.Include(x => x.fk_TheLoaiPhim)
                      select s;//Truy vấn tất cả các phim từ cơ sở dữ liệu.

            if (!String.IsNullOrEmpty(searchString))//Nếu có giá trị tìm kiếm, lọc các phim theo tên phim, diễn viên hoặc đạo diễn.
            {
                phim = phim.Where(s => s.tenPhim.Contains(searchString) 
                                       || s.dienVien.Contains(searchString) 
                                       || s.daoDien.Contains(searchString));
            }

            int pageSize = 5;//Đặt kích thước trang là 5.
            return View(await phanTrang<Phim>.CreateAsync(phim.AsNoTracking(), pageNumber ?? 1, pageSize));//Trả về view với danh sách các phim được phân trang.
        }

        // GET: Phims/Details/5
        public async Task<IActionResult> Details(int? id)//Phương thức này xử lý yêu cầu GET để hiển thị chi tiết của một phim theo id.
        {
            if (id == null)//Nếu id là null, trả về kết quả không tìm thấy.
            {
                return NotFound();
            }

            var phim = _context.Phim.Include(p => p.fk_TheLoaiPhim).FirstOrDefault();
            if (phim == null)//Nếu không tìm thấy phim, trả về kết quả không tìm thấy.
            {
                return NotFound ();
            }
            await _context.SaveChangesAsync();
            return View(phim);//Trả về view với thông tin chi tiết của phim.

        }

        // GET: Phims/Create
        public IActionResult Create()//Phương thức này xử lý yêu cầu GET để hiển thị form tạo phim mới.
        {
            ViewData["TheLoaiPhimList"] = new SelectList(_context.TheLoaiPhim, "id", "tenLoaiPhim");//Tạo danh sách các thể loại phim để hiển thị trong dropdown list.
            return View();//Trả về view với form tạo phim.
        }

        // POST: Phims/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]//Đánh dấu phương thức này để xử lý yêu cầu POST.
        [ValidateAntiForgeryToken]//Bảo vệ chống lại các cuộc tấn công CSRF.
        public async Task<IActionResult> Create([Bind("id, posterPhim, tenPhim, daoDien, dienVien, maLoaiPhim, thoiGianKhoiChieu, thoiLuong, ngonNgu")] Phim phim)//Phương thức này xử lý dữ liệu từ form tạo phim.
        {
            if (ModelState.IsValid) //Kiểm tra tính hợp lệ của dữ liệu.
            {
                bool phimExists = await _context.Phim.AnyAsync(p =>//Kiểm tra xem phim đã tồn tại trong cơ sở dữ liệu chưa.
                p.posterPhim == phim.posterPhim &&
                p.tenPhim == phim.tenPhim &&
                p.daoDien == phim.daoDien &&
                p.dienVien == phim.dienVien &&
                p.maLoaiPhim == phim.maLoaiPhim &&
                p.thoiGianKhoiChieu == phim.thoiGianKhoiChieu &&
                p.thoiLuong == phim.thoiLuong &&
                p.ngonNgu == phim.ngonNgu);

                if (phimExists)//Nếu phim đã tồn tại, thêm lỗi vào ModelState và trả về view với thông báo lỗi.
                {
                    ModelState.AddModelError("", "Bộ phim đã tồn tại.");
                    return View(phim);
                }
                _context.Add(phim); //Thêm phim mới vào cơ sở dữ liệu
                await _context.SaveChangesAsync();//lưu thay đổi.
                return RedirectToAction(nameof(Index));//Chuyển hướng về trang danh sách phim sau khi thêm thành công.
            }
            ViewData["TheLoaiPhimList"] = new SelectList(_context.TheLoaiPhim, "id", "tenPhong", phim.maLoaiPhim);
            return View(phim);
        }

        // GET: Phims/Edit/5
        public async Task<IActionResult> Edit(int? id)//Phương thức này xử lý yêu cầu GET để hiển thị form chỉnh sửa phim theo id.
        {
            if (id == null)//Nếu id là null, trả về kết quả không tìm thấy.
            {
                return NotFound();
            }

            var phim = await _context.Phim.FindAsync(id);//Tìm phim theo id.
            if (phim == null)//Nếu không tìm thấy phim, trả về kết quả không tìm thấy.
            {
                return NotFound();
            }
            ViewData["TheLoaiPhimList"] = new SelectList(_context.TheLoaiPhim, "id", "tenLoaiPhim");
            return View(phim);
        }

        // POST: Phims/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id, posterPhim, tenPhim, daoDien, dienVien, maLoaiPhim, thoiGianKhoiChieu, thoiLuong, ngonNgu")] Phim phim)//Phương thức này xử lý dữ liệu từ form chỉnh sửa phim.
        {
            if (id != phim.id)//Nếu id không khớp với id của phim, trả về kết quả không tìm thấy.
            {
                return NotFound();
            }

            if (ModelState.IsValid)// Kiểm tra tính hợp lệ của dữ liệu.
            {
                //Cập nhật phim trong cơ sở dữ liệu và xử lý các lỗi cập nhật đồng thời.
                try
                {
                    _context.Update(phim);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhimExists(phim.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TheLoaiPhimList"] = new SelectList(_context.TheLoaiPhim, "id", "tenPhong", phim.maLoaiPhim);
            return View(phim);
        }

        // GET: Phims/Delete/5
        public async Task<IActionResult> Delete(int? id)//Phương thức này xử lý yêu cầu GET để hiển thị form xác nhận xóa phim theo id.
        {
            if (id == null)//Nếu id là null, trả về kết quả không tìm thấy.
            {
                return NotFound();
            }

            var phim = await _context.Phim.Include(P => P.fk_TheLoaiPhim)
                .FirstOrDefaultAsync(m => m.id == id);
            if (phim == null)
            {
                return NotFound();
            }

            return View(phim);
        }

        // POST: Phims/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)//Phương thức này xử lý yêu cầu POST để xác nhận xóa phim theo id.
        {
            var phim = await _context.Phim.FindAsync(id);//Tìm phim theo id.
            if (phim != null)//Nếu tìm thấy phim, xóa nó khỏi cơ sở dữ liệu.
            {
                _context.Phim.Remove(phim);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhimExists(int id)//Phương thức này kiểm tra xem phim có tồn tại trong cơ sở dữ liệu hay không dựa vào id.
        {
            return _context.Phim.Any(e => e.id == id);//Trả về true nếu có phim với id được chỉ định, ngược lại trả về false.
        }
        public async Task<IActionResult> NowShowing()
        {
            var NowShowing = await _context.Phim
                 .Where(p => p.thoiGianKhoiChieu <= DateTime.Now)
                 .ToListAsync();

            return View(NowShowing);
        }
        // GET: Movies/Upcoming
        public async Task<IActionResult> Upcoming()
        {
            var UpComing = await _context.Phim
                .Where(p => p.thoiGianKhoiChieu > DateTime.Now)
                .ToListAsync();

            return View(UpComing);
        }
    }
}

DatVeXemPhim/Views/Home/Dangky.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DatVeXemPhim/Views/Home/Dangnhap.cshtml
@{
    Layout = "_LoginLayout";
    ViewBag.Title = "Login";
}

<head>
    <link href="~/css/style.css" rel="stylesheet" />
</head>

<body>
    <section class="container">
        <div class="login-container">
            <div class="circle circle-one"></div>
            <div class="form-container">
                <img src="https://raw.githubusercontent.com/hicodersofficial/glassmorphism-login-form/master/assets/illustration.png" alt="illustration" class="illustration" />
                <h1 class="opacity">ĐĂNG NHẬP</h1>
                <form asp-controller="Accounts" asp-action="Login" method="post">
                    <input type="text" id="username" name="username" placeholder="Nhập tên đăng nhập" />
                    <input type="password" id="password" name="password" placeholder="Nhập mật khẩu" />
                    <button class="opacity">Đăng nhập</button>
                    <div class="pt-1 mb-4">
                        @if (ViewBag.ErrorMessage != null)
                        {
                            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
                        }
                    </div>
                </form>
            </div>
            <div class="circle circle-two"></div>
        </div>
        <div class="theme-btn-container"></div>

    </section>
</body>

<script src="~/js/script.js"></script>

DatVeXemPhim/Views/Home/Details.cshtml
@model DatVeXemPhim.Models.Phim


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Model.tenPhim</title>
    <style>
        /* Global styles */
      

        .container h1 {
            font-size: 2.5rem;
            font-weight: bold;
            margin-bottom: 20px;
            color: #fff;
        }

        .img-fluid {
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            height:100x;
            width: 100%;
            object-fit: cover;
        }

        .movie-details {
            color: #fff;
        }

        .movie-details h1 {
            color: #ffcc00;

        }

        .movie-details p {
            font-size: 1.1rem;
            line-height: 1.5;
            margin-bottom: 10px;
        }

        .btn-primary {
            background-color: #007bff;
            border: none;
            padding: 10px 20px;
            font-size: 1rem;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

            .btn-primary:hover {
                background-color: #0056b3;
            }

        .btn-secondary {
            background-color: #6c757d;
            border: none;
            padding: 10px 20px;
            font-size: 1rem;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .btn-secondary:hover {
            background-color: #5a6268;
        }

        .d-flex {
            align-items: center;
        }

    </style>
</head>
<body>
    <div class="container my-5">
        <h1>Nội dung phim</h1>
        <div class="row">
            <div class="col-md-4">
                <img src="@Model.posterPhim" class="img-fluid" alt="@Model.tenPhim">
            </div>
            <div class="col-md-8 movie-details">
                <h1>@Model.tenPhim</h1>
                <p>Đạo diễn: @Model.daoDien</p>
                <p>Diễn viên: @Model.dienVien</p>
                <p>Thể loại: @Model.fk_TheLoaiPhim.tenLoaiPhim</p>
                <p>Khởi chiếu: @Model.thoiGianKhoiChieu.ToString("dd/MM/yyyy")</p>
                <p>Thời lượng: @Model.thoiLuong</p>
                <p>Ngôn ngữ: @Model.ngonNgu</p>
                <div class="d-flex justify-content-between mt-4">
                    <a href="#" class="btn btn-primary">Mua vé</a>
                    <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Quay lại</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

DatVeXemPhim/Views/Home/Index.cshtml
@model IEnumerable<DatVeXemPhim.Models.Phim>
@{
    ViewData["Title"] = "Trang chủ";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My ASP.NET Application</title>
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="https://unpkg.com/swiper/swiper-bundle.min.css" rel="stylesheet" />
</head>
<body>
    <section id="portfolio-details" class="portfolio-details">
        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-8">
                    <div class="portfolio-details-slider swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/vvd6l0K.jpeg">
                            </div>
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/ZAsFRGV.png">
                            </div>
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/NdkeTHe.jpeg">
                            </div>
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/HFatZYJ.jpeg">
                            </div>
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/8oj3EkB.jpeg">
                            </div>
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/7Ct45cq.png">
                            </div>
                            <div class="swiper-slide">
                                <img src="https://i.imgur.com/o62EDEu.png">
                            </div>
                        </div> 
                        <div class="swiper-pagination"></div>
                    </div>
                   
                </div>
            </div>
            <h1>TOP 5 BỘ PHIM HOT NHẤT</h1>
            <div class="movie-list">
                <div class="col-lg-8">
                    @foreach (var movie in Model.OrderBy(m => Guid.NewGuid()).Take(5))
                    {
                        <div class="movie-item" style="">
                            <img src="@movie.posterPhim" alt="@movie.tenPhim">
                            <div class="movie-details">
                                <div class="movie-title">@movie.tenPhim</div>
                                <div class="movie-description">Đạo diễn: @movie.daoDien</div>
                                <div class="movie-description">Diễn viên: @movie.dienVien</div><br>
                                <a asp-controller="Home" asp-action="Details" asp-route-id="@movie.id"><button class="btn btn-warning">Xem chi tiết</button></a>
                                <a asp-controller="KhachDatVe" asp-action="Step2" asp-route-id="@movie.id" class=" btn btn-primary">Đặt vé</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        </div>
    </section>

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var swiper = new Swiper('.swiper-container', {
                spaceBetween: 1000,
                centeredSlides: true,
                autoplay: {
                    delay: 2000,
                    disableOnInteraction: false,
                },
                loop:true,
                pagination: {
                    el: '.swiper-pagination',
                    clickable: true,
                },
                
            });
        });
    </script>
</body>
</html>

DatVeXemPhim/Views/Home/Phim.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Hello from our View Template!</p>

DatVeXemPhim/Views/Home/Rap.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DatVeXemPhim/Views/Home/Search.cshtml
@model IEnumerable<DatVeXemPhim.Models.Phim>

<h1 class="mb-4">Kết quả tìm kiếm từ khóa "@ViewBag.SearchString"</h1>

<div class="movie-list">
    <div class="col-lg-8">
        @foreach (var movie in Model)
        {
            <div class="movie-item" style="">
                <img src="@movie.posterPhim" alt="@movie.tenPhim">
                <div class="movie-details">
                    <div class="movie-title">@movie.tenPhim</div>
                    <div class="movie-description">Đạo diễn: @movie.daoDien</div>
                    <div class="movie-description">Diễn viên: @movie.dienVien</div><br>
                    <a asp-controller="Home" asp-action="Details" asp-route-id="@movie.id"><button class="btn btn-warning">Xem chi tiết</button></a>
                </div>
            </div>
        }
    </div>
</div>

DatVeXemPhim/Views/Home/Tintuc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DatVeXemPhim/Views/Home/VeDaDat.cshtml
@model IEnumerable<DatVeXemPhim.Models.Ve>
@if (Model == null)
{
    <h1>Danh sách trống</h1>
}
else
{
    <div class="container mt-4">
        <h1 class="text-center mb-4">@ViewData["Vé đã đặt"]</h1>

        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Mã vé</th>
                        <th>Tên phim</th>
                        <th>Giờ chiếu</th>
                        <th>Ghế</th>
                        <th>Phòng</th>
                        <th>Giá</th>
                        <th>Thời gian đặt</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.id</td>
                            <td>@Html.DisplayFor(modelItem => item.fk_XuatChieu.fk_Phim.tenPhim)</td>
                            <td>@Html.DisplayFor(modelItem => item.fk_XuatChieu.ngayChieu)</td>
                            <td>@Html.DisplayFor(modelItem => item.fk_MaGhe.tenGhe)</td>
                            <td>@Html.DisplayFor(modelItem => item.fk_MaGhe.fk_PhongChieu.tenPhong)</td>
                            <td>@Html.DisplayFor(modelItem => item.tongTien)</td>
                            <td>@Html.DisplayFor(modelItem => item.ngayBanVe)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}